In [0]:
import torch
import numpy as np
import pandas as pd

# Trabajando con tensores

In [0]:
torch.__version__

'1.3.1'

In [0]:
tensor_a = torch.ones(2, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [0]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0, 1)

tensor([[2.0096e-36, 0.0000e+00],
        [3.7835e-44, 0.0000e+00]])


tensor([[0.0016, 0.8143],
        [0.9784, 0.3117]])

In [0]:
tensor_c = torch.rand(2, 2)
tensor_c

tensor([[0.5205, 0.9008],
        [0.4485, 0.9716]])

In [0]:
result = tensor_a + tensor_b
result

tensor([[1.0016, 1.8143],
        [1.9784, 1.3117]])

In [0]:
result.shape
reshaped = result.view(4,1)
reshaped

tensor([[1.0016],
        [1.8143],
        [1.9784],
        [1.3117]])

In [0]:
points = torch.tensor([[1.0,2.0],[3.0, 4.0]])
print(points)
points[0][1] =  2.5
print(points)
points.storage()

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


 1.0
 2.5
 3.0
 4.0
[torch.FloatStorage of size 4]

In [0]:
points, points.stride()

In [0]:
p_t = points.t()
p_t , p_t.stride()

(tensor([[1.0000, 3.0000],
         [2.5000, 4.0000]]), (1, 2))

In [0]:
tensor_x = torch.tensor([1,2,3,4])
#tensor_x, torch.unsqueeze(tensor_x, 0)
tensor_x, torch.unsqueeze(tensor_x, 1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [0]:
numpyArray = np.random.randn(2,2)
from_numpy = torch.from_numpy(numpyArray)

# Representar datos con tensores

In [0]:
print(from_numpy)

print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([[ 0.0101, -0.6923],
        [ 0.8385, -1.0621]], dtype=torch.float64)
tensor(-0.2264, dtype=torch.float64)
tensor([ 0.4243, -0.8772], dtype=torch.float64)
tensor([-0.3411, -0.1118], dtype=torch.float64)


In [0]:
torch.std(from_numpy, dim=1)


In [0]:
load = torch.save(from_numpy, 'tensor.t')
load

In [0]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [0]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [0]:
subset = dataframe[['Overall', 'Age', 'International Reputation', 'Weak Foot', 'Skill Moves']].dropna(axis=0, how='any')
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape , players.type()

In [0]:
data = players[:, 1:]
data, data.shape

In [0]:
target = players[:, 0]
target, target.shape

In [0]:
mean = torch.mean( data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [0]:
std = torch.std( data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [0]:
norm = (data - mean)/torch.sqrt(std)
norm

In [0]:
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
notSoGood = data[torch.le(target, 70)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
notSoGoodMean = torch.mean(notSoGood, dim=0)

# goodMean, averageMean, notSoGoodMean

for i, args in enumerate(zip(columns, goodMean, averageMean, notSoGoodMean)):
  print('{:25} {:0.2f} {:6.2f}'.format(*args))

Age                       28.35  27.23
International Reputation  3.38   1.36
Weak Foot                 3.45   3.11
Skill Moves               3.04   2.75
